_BASE_: "./Base-RCNN-FPN-OPENDET.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
DATASETS:
  # TRAIN: ('voc_2007_train', 'voc_2012_trainval')
  TRAIN: ('voc_2007_trainval', )
  TEST: ('coco-unlabel', )
  # TEST: ('voc_2007_test', 'voc_coco_20_40_test', 'voc_coco_20_60_test', 'voc_coco_20_80_test', 'voc_coco_2500_test', 'voc_coco_5000_test', 'voc_coco_10000_test', 'voc_coco_20000_test')
SOLVER:
  WEIGHT_DECAY_BIAS: 0.0
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (168000, 232000)
  MAX_ITER: 256000
  WARMUP_ITERS: 800
  AMP:
    ENABLED: True
OUTPUT_DIR: "/home/lingxiao/lzy/opendet/opendet2/output/inference-trash"
# UPLOSS.WEIGHT: former two are 0.5, the last is 1.0